"""docs_ids_not_nullable

Revision ID: 0ce2bd7afddf
Revises: 19c6d29f0a65
Create Date: 2026-06-06 00:04:48.944136

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ce2bd7afddf'
down_revision: Union[str, Sequence[str], None] = '19c6d29f0a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'vector_id')
    op.alter_column('document_chunk', 'chat_session_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunk', 'chat_session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('document', sa.Column('vector_id', sa.UUID(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
