"""document_ids_now_nullable

Revision ID: 19c6d29f0a65
Revises: 4d8e7f0c3b1d
Create Date: 2026-06-05 23:13:01.715923

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "19c6d29f0a65"
down_revision: Union[str, Sequence[str], None] = "4d8e7f0c3b1d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document", "id", existing_type=sa.UUID(), nullable=True)
    op.drop_column("document", "vector_id")
    op.alter_column(
        "document_chunk", "document_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "document_chunk", "chat_session_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunk", "chat_session_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "document_chunk", "document_id", existing_type=sa.UUID(), nullable=False
    )
    op.add_column(
        "document",
        sa.Column("vector_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.alter_column("document", "id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
