"""document_ids_now_nullable

Revision ID: 19c6d29f0a65
Revises: 4d8e7f0c3b1d
Create Date: 2026-06-05 23:13:01.715923

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19c6d29f0a65"
down_revision: str | Sequence[str] | None = "4d8e7f0c3b1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunk", "document_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "document_chunk", "document_id", existing_type=sa.UUID(), nullable=False
    )
    # ### end Alembic commands ###
