"""added user model

Revision ID: 60c66aadc3fd
Revises: f1b73492f806
Create Date: 2026-04-01 14:51:37.063185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60c66aadc3fd'
down_revision: Union[str, Sequence[str], None] = 'f1b73492f806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_created_at'), 'user', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_expires_at'), 'user', ['expires_at'], unique=False)
    op.create_index(op.f('ix_user_last_seen_at'), 'user', ['last_seen_at'], unique=False)
    op.add_column('chat_session', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'chat_session', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_session', type_='foreignkey')
    op.drop_column('chat_session', 'user_id')
    op.drop_index(op.f('ix_user_last_seen_at'), table_name='user')
    op.drop_index(op.f('ix_user_expires_at'), table_name='user')
    op.drop_index(op.f('ix_user_created_at'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
