"""removed user.expires_at

Revision ID: 91a8087f2fa8
Revises: 60c66aadc3fd
Create Date: 2026-04-07 18:02:35.272281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91a8087f2fa8'
down_revision: Union[str, Sequence[str], None] = '60c66aadc3fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_session', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(op.f('chat_session_user_id_fkey'), 'chat_session', type_='foreignkey')
    op.create_foreign_key(None, 'chat_session', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_user_expires_at'), table_name='user')
    op.drop_column('user', 'expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_user_expires_at'), 'user', ['expires_at'], unique=False)
    op.drop_constraint(None, 'chat_session', type_='foreignkey')
    op.create_foreign_key(op.f('chat_session_user_id_fkey'), 'chat_session', 'user', ['user_id'], ['id'])
    op.alter_column('chat_session', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
