"""ensured consistent datetime formatting

Revision ID: ab093f35d788
Revises: 91a8087f2fa8
Create Date: 2026-04-07 18:26:19.724912

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'ab093f35d788'
down_revision: str | Sequence[str] | None = '91a8087f2fa8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
