"""updated columns

Revision ID: ce05f8fa413a
Revises: ab093f35d788
Create Date: 2026-04-09 14:48:08.875178

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'ce05f8fa413a'
down_revision: str | Sequence[str] | None = 'ab093f35d788'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
