"""doc_id mandatory in DocumentChunk and removed total_messagess from ChatSession

Revision ID: ff3dea15a12f
Revises: 33add43b7de8
Create Date: 2026-07-16 11:37:29.056402

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ff3dea15a12f'
down_revision: str | Sequence[str] | None = '33add43b7de8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_session', 'total_messages')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_session', sa.Column('total_messages', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
