"""
Responsible for handling user queries and generating their corresponding
response.
"""

from typing import List, Tuple
from uuid import UUID

from langchain_openai import ChatOpenAI
from langchain_core.output_parsers import StrOutputParser

from src.api.services.validation.rag_validation import validate_and_sanitize_query
from src.config.configs import settings
from src.components.prompts.prompt_loader import create_prompt_template
from src.components.retrieval.embedder import Embedder
from src.database.models import DocumentChunk
from src.database.repository.interfaces.document_chunk_repository import (
    DocumentChunkRepositoryInterface,
)

from src.logger.base_logger import BaseLogger


class QueryHandler:
    """
    Handles the query processing and the response generation.
    """

    def __init__(
        self, embedder: Embedder, document_chunk_repo: DocumentChunkRepositoryInterface
    ) -> None:
        """
        Initializes the QueryHandler instance.

        Args:
            embedder: The class instance used to create embeddings for indexes.
        """
        self.embedder = embedder
        self.document_chunk_repo = document_chunk_repo
        self._llm = ChatOpenAI(
            model=settings.llm.LLM_MODEL_NAME, temperature=settings.llm.LLM_TEMPERATURE
        )
        self._prompt_template = create_prompt_template(
            settings.llm.RESPONSE_PROMPT_FILEPATH
        )
        self._logger = BaseLogger(__name__)

    async def search_for_vector(
        self, query: str, chat_session_id: UUID
    ) -> Tuple[List[DocumentChunk], List[str]]:
        """
        Embeds query, searches vector DB, returns top_k results.
        """

        query = validate_and_sanitize_query(query, self._logger)

        self._logger.debug("Embedding queries now...")

        query_vector = self.embedder.embed_query(query)

        self._logger.debug("Initialing vector search...")

        chunks: List[DocumentChunk] = await self.document_chunk_repo.search_similar(
            chat_session_id=chat_session_id,
            vector=query_vector,
            top_k=settings.vector.RETRIEVAL_TOP_K,
            threshold=settings.vector.SIMILARITY_THRESHOLD,
        )

        sources: List[str] = await self.document_chunk_repo.get_filenames_for_chunks(
            chunks=chunks,
            chat_session_id=chat_session_id,
        )

        if not chunks or len(chunks) == 0:
            self._logger.error(
                f"No vector chunks found for the query vector: {query_vector}"
            )
            return [], []

        self._logger.info(f"Results found for the query: {query}")

        return chunks, sources

    def generate_responses(
        self,
        query: str,
        retrieved_chunks: List[DocumentChunk],
        from_web_search: bool = False,
    ) -> str | None:
        """
        Formats a prompt with the query and retrieved chunks, then passes it
        to an LLM.
        """

        if not retrieved_chunks or len(retrieved_chunks) == 0:
            self._logger.warning(
                "No retrieved chunks provided for response generation."
            )
            return None

        self._logger.debug(f"Generating responses for the query: {query}")

        context_text = "\n\n".join([chunk.chunk_text for chunk in retrieved_chunks])

        # Create a chain for processing
        rag_chain = self._prompt_template | self._llm | StrOutputParser()

        response = rag_chain.invoke({"context": context_text, "query": query})

        if response.strip() == "NEED_WEB_SEARCH" and not from_web_search:
            return None

        self._logger.debug("Response generated by LLM.")

        return response
